
INSERT INTO EVENT_STATUS (status_type)
VALUES ('TO_APPROVE');
INSERT INTO EVENT_STATUS (status_type)
VALUES ('TODO');
INSERT INTO EVENT_STATUS (status_type)
VALUES ('IN_PROGRESS');
INSERT INTO EVENT_STATUS (status_type)
VALUES ('REVIEW');
INSERT INTO EVENT_STATUS (status_type)
VALUES ('DONE');

INSERT INTO STATUS_PERMISSION (status_type)
VALUES ('SPECIAL');
INSERT INTO STATUS_PERMISSION (status_type)
VALUES ('CANCELED');
INSERT INTO STATUS_PERMISSION (status_type)
VALUES ('APPROVED');
INSERT INTO STATUS_PERMISSION (status_type)
VALUES ('REQUEST');

INSERT INTO BOOKING (booking_type)
VALUES ('PHOTOGRAPHY');
INSERT INTO BOOKING(booking_type)
VALUES ('FILM');
INSERT INTO BOOKING (booking_type)
VALUES ('MARKETING');
INSERT INTO BOOKING (booking_type)
VALUES ('OTHER');

INSERT INTO EVENT_TYPE (event_type)
VALUES ('WEDDING');
INSERT INTO EVENT_TYPE (event_type)
VALUES ('CLUB');
INSERT INTO EVENT_TYPE (event_type)
VALUES ('BUSINESS');
INSERT INTO EVENT_TYPE (event_type)
VALUES ('FESTIVAL');
INSERT INTO EVENT_TYPE (event_type)
VALUES ('COMMERCIAL');

INSERT INTO DEPARTMENT (department_type)
VALUES ('EVENT_PHOTOGRAPHY');
INSERT INTO DEPARTMENT (department_type)
VALUES ('EVENT_FILMMAKING');
INSERT INTO DEPARTMENT (department_type)
VALUES ('CLUB_PHOTOGRAPHY');
INSERT INTO DEPARTMENT (department_type)
VALUES ('MARKETING');

INSERT INTO PROJECT_ROLE(project_role_type)
VALUES ('FILMMAKER');
INSERT INTO PROJECT_ROLE(project_role_type)
VALUES ('PHOTOGRAPHER');
INSERT INTO PROJECT_ROLE(project_role_type)
VALUES ('PRODUCTION');

INSERT INTO AVAILABILITY (availability_type)
VALUES ('VACATION');
INSERT INTO AVAILABILITY(availability_type)
VALUES ('AVAILABLE');
INSERT INTO AVAILABILITY (availability_type)
VALUES ('RETIRED');

INSERT INTO SERVER_ROLE (server_role_type)
VALUES ('CLIENT');
INSERT INTO SERVER_ROLE (server_role_type)
VALUES ('ADMIN');
INSERT INTO SERVER_ROLE (server_role_type)
VALUES ('CREW');

INSERT INTO URGENCY(urgency_type)
VALUES('LEVEL_1');
INSERT INTO URGENCY(urgency_type)
VALUES('LEVEL_2');
INSERT INTO URGENCY(urgency_type)
VALUES('LEVEL_3');

